# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Compile lab 1
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: reports/source/lab_1/
    - name: Compile lab 2
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: reports/source/lab_2/
         
    - name: Compile lab 3
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: reports/source/lab_3/
        
        
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: reports
        path: reports/source
      if: always()  
        


